# Generated by Django 2.2.14 on 2020-07-28 11:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_userinfo_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None),
        ),
    ]
