# Generated by Django 2.2.14 on 2020-07-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200728_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
